.TH PIC-TOOL 1

.SH NAME

image_thumbnailer \- Thumbnail the image in the Command line.

.SH SYNOPSIS

.B image_thumbnailer
[\fB\-s\fR \fR]
[\fB\-d\fR \fR]
[\fB\-\-hei \fINumber\fR \fR]
[\fB\-\-wid \fINumber\fR \fR]
[\fB\-\-img \fIPATH\fR \fR] ...

.SH DESCRIPTION
.B image_thumbnailer 
is a part of pic-tool this tool thumbnail the image.

.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Show help and exit.

.TP
.BR \-d ", " \-\-dir
Use this flag to set the tool to directory mode.

.TP
.BR \-s ", " \-\-single  
Use this flag to set the tool to Single mode.

.TP
.BR \-\-img
Use to give the path of image and directory. Necessary.

.TP
.BR \-\-hei
Provide the Width of thumbnail, Default : 250

.TP
.BR \-\-hei 
Provide the Height of thumbnail, Default : 250

.SH AUTHOUR

Name = 
.B Ashwini Sahu 

Github = https.//github.com/ASHWIN990/pic-tool
