.TH PIC-TOOL 1

.SH NAME

image_ext_change \- Change the extension of the image in the Command line.

.SH SYNOPSIS

.B image_ext_change
[\fB\-sm\fR \fR]
[\fB\-dm\fR \fR]
[\fB\-\-ext\fR \fIEXT\fR]
[\fB\-\-img \fIPATH\fR \fR] ...

.SH DESCRIPTION
.B image_ext_change
is a part of pic-tool this tool changes the extensions of the image.

.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Show help and exit.

.TP
.BR \-d ", " \-\-dir
Use this flag to set the tool to directory mode.

.TP
.BR \-s ", " \-\-single  
Use this flag to set the tool to Single mode.

.TP
.BR \-\-img
Use to give the path of image and directory. Necessary.

.TP
.BR \-\-ext
Provide the new image extension.

.SH AUTHOUR

Name = 
.B Ashwini Sahu 

Github = https.//github.com/ASHWIN990/pic-tool
