.TH PIC-TOOL 1

.SH NAME

image_rotate \- Rotate the image in the Command line.

.SH SYNOPSIS

.B image_rotate
[\fB\-sm\fR \fR]
[\fB\-dm\fR \fR]
[\fB\-\-rot \fIROTATION\fR \fR]
[\fB\-\-img \fIPATH\fR \fR] ...

.SH DESCRIPTION
.B image_rotate
is a part of pic-tool this tool rotate the image.

.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Show help and exit.

.TP
.BR \-d ", " \-\-dir
Use this flag to set the tool to directory mode.

.TP
.BR \-s ", " \-\-single  
Use this flag to set the tool to Single mode.

.TP
.BR \-\-img
Use to give the path of image and directory. Necessary.

.TP
.BR \-\-rot
Provide the Degree of Rotation of new image, Default : 180, Range (0-360).

.SH AUTHOUR

Name = 
.B Ashwini Sahu 

Github = https.//github.com/ASHWIN990/pic-tool
