.TH PIC-TOOL 1

.SH NAME

image_greyscale \- Greyscale the image in the Command line.

.SH SYNOPSIS

.B image_greyscale
[\fB\-sm\fR \fR]
[\fB\-dm\fR \fR]
[\fB\-\-img \fIPATH\fR \fR] ...

.SH DESCRIPTION
.B image_greyscale
is a part of pic-tool this tool greyscale the image.

.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Show help and exit.

.TP
.BR \-d ", " \-\-dir
Use this flag to set the tool to directory mode.

.TP
.BR \-s ", " \-\-single  
Use this flag to set the tool to Single mode.

.TP
.BR \-\-img
Use to give the path of image and directory. Necessary.

.SH AUTHOUR

Name = 
.B Ashwini Sahu 

Github = https.//github.com/ASHWIN990/pic-tool
