.TH PIC-TOOL 1

.SH NAME

pic-tool \- Image manipulation tool writeen in python.

.SH SYNOPSIS

.B pic-tool
[\fB\-sm\fR \fR]
[\fB\-dm\fR \fR]
[\fB\-na\fR \fR] ...

.SH DESCRIPTION
.B pic-tool 
is an image manipulation tool writeen in python, and work in CLI. This project is made for he folks who don't want to upload images online to unknown websites for tasks like :-

1. Image Resizing 

2. Image Compressing 

3. Thumbnailing Image

4. Image Format Changer 

5. Rotating Image

6. Greyscale Image

7. Image Metadata Remover

  ... More to be added ...

.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Show help and exit.

.TP
.BR \-d ", " \-dm ", " \-\-dir\-mode
Use this flag to set the tool to directory mode.

.TP
.BR \-s ", " \-sm ", " \-\-sin\-mode  
Use this flag to set the tool to Single mode. Default is set to single mode.

.TP
.BR \-\-nc ", " \-\-no\-clear
Using this flag doesnt clear the terminal.

.TP
.BR \-\-na ", " \-\-no\-art
This flag doesn't print the ASCII art.

.SH AUTHOUR

Name = 
.B Ashwini Sahu 

Github = https.//github.com/ASHWIN990/pic-tool
